### ISSUE TITLE
Add a feature to change video quality from the video player

### ISSUE THREAD

**Issue by shinpie** [AZoneLive/PersonalZone#4]
There is  no feature  to change the video quality, It's available on Aniyomi (tachiyomi-mi), if you want a reference. 

I like to watch anime in lower quality to save data, so it would be very helpful to people like me.

Thankyou.

**Comment by AZoneLive** [comment]
> There is no feature to change the video quality, It's available on Aniyomi (tachiyomi-mi), if you want a reference.
> 
> I like to watch anime in lower quality to save data, so it would be very helpful to people like me.
> 
> Thankyou.

Sorry, this is a modified version of AnimeZone with a patch to fix the startup crash and allow it to run. Since AZ was made with Flutter, it's physically impossible to decompile. The patch done here needed a few value modifications, nothing that required me to have the original source code. However, modifying the video player would. As much as I would love to make this app my own and fix the issues and add features, it's just impossible to do with the current state of Flutter.

**Comment by vsy2876** [comment]
> There is no feature to change the video quality, It's available on Aniyomi (tachiyomi-mi), if you want a reference.
> 
> I like to watch anime in lower quality to save data, so it would be very helpful to people like me.
> 
> Thankyou.

If the server offers multiple qualities it can be changed from within the media player itself
